# 数据设置
data_dir: Data
data_files:
  - ../Data/FM_original.csv
  - ../Data/OD_original.csv
  - ../Data/MEFAR_original.csv
block_col: block
feature_cols: [acc_x, acc_y, acc_z, ppg, gsr, hr, skt]
sample_rate: 32
window_sec: 10.0
step_sec: 3.0
window_size: 320
step_size: 96
norm_method: zscore
train_split: 0.8

# 训练设置
batch_size: 32
epochs: 200
lr: 0.0005
patience: 20
log_dir: Logs
ckpt_dir: Checkpoints

# 模型结构
model:
  in_channels: 7  # 与 feature_cols 对应
  hidden_channels: 64
  out_channels: 7
  encoder_layers: 3
  decoder_layers: 3
  heads: 4
  trans_nhead: 4
  trans_layers: 2
  trans_dim_feedforward: 512
  use_skip: true
  use_attention_feedback: true

  # GSL 子模块配置
  gsl:
    top_k: 3
